# Generated by Django 3.0.3 on 2020-02-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_student_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='upload',
            field=models.FileField(blank=True, null=True, upload_to='homeworks/%Y/%m/%d/'),
        ),
    ]
