# Generated by Django 3.0.3 on 2020-03-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200229_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
