# Generated by Django 3.0.3 on 2020-03-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20200308_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='group',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
