# Generated by Django 3.0.7 on 2020-06-04 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
    ]
