# Generated by Django 3.0.7 on 2020-06-17 05:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teststudent',
            options={'ordering': ('-date_pub',), 'verbose_name': 'Тест Студент', 'verbose_name_plural': 'Тесты Студенты'},
        ),
        migrations.AddField(
            model_name='teststudent',
            name='date_pub',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 6, 17, 5, 37, 23, 915002, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teststudent',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
