# Generated by Django 3.0.7 on 2020-06-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_auto_20200604_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
