# Generated by Django 3.0.7 on 2020-06-06 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_auto_20200605_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='password',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Group'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.TextField(max_length=200),
        ),
    ]
