# Generated by Django 3.0.7 on 2020-06-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0008_auto_20200606_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='lesson',
            field=models.FileField(upload_to='lessons/'),
        ),
    ]
