# Generated by Django 3.0.7 on 2020-06-08 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0009_auto_20200606_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='completed',
        ),
        migrations.AlterField(
            model_name='homework',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='panel.Group'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homework',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.Student'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='lesson',
            field=models.FileField(upload_to='lessons/%Y/%m/%d/'),
        ),
    ]
