# Generated by Django 3.0.7 on 2020-06-13 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0011_test_testanswer_testitem_teststudent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testanswer',
            options={'verbose_name': 'Тест ответы', 'verbose_name_plural': 'Тесты ответы'},
        ),
        migrations.AddField(
            model_name='testanswer',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='panel.Test'),
            preserve_default=False,
        ),
    ]
