# Generated by Django 3.0.7 on 2020-06-13 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0012_auto_20200613_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testitem',
            name='answer',
        ),
    ]
