# Generated by Django 3.0.7 on 2020-06-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0013_remove_testitem_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='testitem',
            name='count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
