# Generated by Django 3.0.7 on 2020-06-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0014_testitem_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='teststudent',
            name='processed',
            field=models.BooleanField(default=True),
        ),
    ]
